name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers only when pushing a version tag like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Adjust as needed

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            **/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Install vsce
        run: yarn global add vsce

      - name: Package extension
        run: vsce package

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.vsix'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
