name: Package VSCode Extension

on:
  push:
    tags:
      - 'v*' # Only build on version tags like v0.1.0

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Install dependencies
        run: npm ci

      - name: Package Extension
        run: vsce package

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.vsix'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
